name:
  StandardFcIP

architecture:
  n_layers: 5
  input_size: 784
  width: 256
  bias: false
  output_size: 10

activation:
  name: "gelu"

loss:
  name: "cross_entropy"
  params:
    reduction: "mean"

optimizer:
  name: "sgd"
  params:
    lr: 1.0e-3

initializer:
  name: "custom"
  params:
    var: 2.0

training:
  batch_size: 128
  n_epochs: 20
  n_steps: 2.0e5